/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project.Frontend;

import Project.Backend.*;
import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS 10
 */
public class inputNilaiSiswa extends javax.swing.JFrame {

   Siswa siswa = new Siswa();
   public String idFoto = "";

   public inputNilaiSiswa() {
      initComponents();
      lblJurusan.setVisible(false);
   }

   public int getJurusan() {
      int jurusan = 0;
      if (radioRpl.isSelected()) {
         jurusan = 1;
      } else if (radioMesin.isSelected()) {
         jurusan = 2;
      } else if (radioTkr.isSelected()) {
         jurusan = 3;
      } else if (radioTkj.isSelected()) {
         jurusan = 4;
      } else if (radioMM.isSelected()) {
         jurusan = 5;
      } else if (radioListrik.isSelected()) {
         jurusan = 6;
      }
      lblJurusan.setText(String.valueOf(jurusan));

      return jurusan;
   }

   public void clearData(){
      txtNilaiBig.setText("");
      txtNilaiBin.setText("");
      txtNilaiIpa.setText("");
      txtNilaiMtk.setText("");
      txtRata.setText("0");
      radioListrik.setSelected(false);
      radioMM.setSelected(false);
      radioMesin.setSelected(false);
      radioRpl.setSelected(false);
      radioTkj.setSelected(false);
      radioTkr.setSelected(false);
   }
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jTextField4 = new javax.swing.JTextField();
      buttonGroup11 = new javax.swing.ButtonGroup();
      jPanel1 = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      txtIdSiswa = new javax.swing.JTextField();
      jPanel4 = new javax.swing.JPanel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      txtNilaiBin = new javax.swing.JTextField();
      jLabel8 = new javax.swing.JLabel();
      txtNilaiMtk = new javax.swing.JTextField();
      txtNilaiBig = new javax.swing.JTextField();
      txtNilaiIpa = new javax.swing.JTextField();
      txtRata = new javax.swing.JTextField();
      btnHitungrata = new javax.swing.JButton();
      btnSimpan = new javax.swing.JButton();
      jPanel5 = new javax.swing.JPanel();
      radioTkj = new javax.swing.JRadioButton();
      radioListrik = new javax.swing.JRadioButton();
      radioRpl = new javax.swing.JRadioButton();
      radioTkr = new javax.swing.JRadioButton();
      radioMesin = new javax.swing.JRadioButton();
      radioMM = new javax.swing.JRadioButton();
      txtNama = new javax.swing.JTextField();
      txtAsalSekolah = new javax.swing.JTextField();
      jPanel3 = new javax.swing.JPanel();
      lblFoto = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      txtAlamat = new javax.swing.JTextArea();
      lblJurusan = new javax.swing.JLabel();

      jTextField4.setBackground(new java.awt.Color(0, 204, 204));
      jTextField4.setForeground(new java.awt.Color(255, 255, 255));

      setTitle("Input Nilai");
      setAlwaysOnTop(true);
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(169, 224, 49));

      jPanel2.setBackground(new java.awt.Color(0, 0, 0));

      jLabel1.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 1, 14)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(255, 255, 255));
      jLabel1.setText("ID SISWA");

      jLabel2.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 1, 14)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(255, 255, 255));
      jLabel2.setText("NAMA");

      jLabel3.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 1, 14)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(255, 255, 255));
      jLabel3.setText("ASAL SEKOLAH");

      txtIdSiswa.setEditable(false);
      txtIdSiswa.setBackground(new java.awt.Color(0, 0, 0));
      txtIdSiswa.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
      txtIdSiswa.setForeground(new java.awt.Color(255, 255, 255));
      txtIdSiswa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      jPanel4.setBackground(new java.awt.Color(0, 0, 0));
      jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 3), " Daftar Nilai Ujian Nasional", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Noto Sans CJK JP Bold", 1, 14), new java.awt.Color(242, 242, 242))); // NOI18N
      jPanel4.setForeground(new java.awt.Color(255, 255, 255));

      jLabel4.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 1, 16)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(255, 255, 255));
      jLabel4.setText("Nilai Matematika");

      jLabel5.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 1, 16)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(255, 255, 255));
      jLabel5.setText("Nilai Bahasa Indonesia");

      jLabel6.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 1, 16)); // NOI18N
      jLabel6.setForeground(new java.awt.Color(255, 255, 255));
      jLabel6.setText("Nilai IPA");

      jLabel7.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 1, 16)); // NOI18N
      jLabel7.setForeground(new java.awt.Color(255, 255, 255));
      jLabel7.setText("Nilai  Bahasa Inggris");

      txtNilaiBin.setBackground(new java.awt.Color(0, 0, 0));
      txtNilaiBin.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 14)); // NOI18N
      txtNilaiBin.setForeground(new java.awt.Color(255, 255, 255));
      txtNilaiBin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      jLabel8.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 1, 16)); // NOI18N
      jLabel8.setForeground(new java.awt.Color(255, 255, 255));
      jLabel8.setText("Nilai Rata - Rata");

      txtNilaiMtk.setBackground(new java.awt.Color(0, 0, 0));
      txtNilaiMtk.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 14)); // NOI18N
      txtNilaiMtk.setForeground(new java.awt.Color(255, 255, 255));
      txtNilaiMtk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      txtNilaiBig.setBackground(new java.awt.Color(0, 0, 0));
      txtNilaiBig.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 14)); // NOI18N
      txtNilaiBig.setForeground(new java.awt.Color(255, 255, 255));
      txtNilaiBig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      txtNilaiIpa.setBackground(new java.awt.Color(0, 0, 0));
      txtNilaiIpa.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 14)); // NOI18N
      txtNilaiIpa.setForeground(new java.awt.Color(255, 255, 255));
      txtNilaiIpa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      txtRata.setEditable(false);
      txtRata.setBackground(new java.awt.Color(0, 0, 0));
      txtRata.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 14)); // NOI18N
      txtRata.setForeground(new java.awt.Color(255, 255, 255));
      txtRata.setText("0");
      txtRata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      btnHitungrata.setBackground(new java.awt.Color(169, 224, 49));
      btnHitungrata.setForeground(new java.awt.Color(0, 0, 0));
      btnHitungrata.setText("Hitung");
      btnHitungrata.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnHitungrataActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel4Layout.createSequentialGroup()
                  .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel5)
                     .addComponent(jLabel4))
                  .addGap(4, 4, 4)
                  .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtNilaiMtk, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtNilaiBin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(jPanel4Layout.createSequentialGroup()
                  .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel7)
                     .addComponent(jLabel6)
                     .addComponent(jLabel8))
                  .addGap(25, 25, 25)
                  .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNilaiIpa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNilaiBig, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(txtRata, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnHitungrata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(txtNilaiMtk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(txtNilaiBin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel7)
               .addComponent(txtNilaiBig, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(txtNilaiIpa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtRata, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnHitungrata, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 21, Short.MAX_VALUE))
      );

      btnSimpan.setBackground(new java.awt.Color(169, 224, 49));
      btnSimpan.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
      btnSimpan.setForeground(new java.awt.Color(0, 0, 0));
      btnSimpan.setText("SIMPAN");
      btnSimpan.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSimpanActionPerformed(evt);
         }
      });

      jPanel5.setBackground(new java.awt.Color(0, 0, 0));
      jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 3), "Daftar Jurusan", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Noto Sans CJK JP Bold", 1, 14), new java.awt.Color(242, 242, 242))); // NOI18N
      jPanel5.setForeground(new java.awt.Color(255, 255, 255));

      radioTkj.setBackground(new java.awt.Color(0, 204, 204));
      buttonGroup11.add(radioTkj);
      radioTkj.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 16)); // NOI18N
      radioTkj.setForeground(new java.awt.Color(255, 255, 255));
      radioTkj.setText("Teknik Komputer Jaringan");

      radioListrik.setBackground(new java.awt.Color(0, 204, 204));
      buttonGroup11.add(radioListrik);
      radioListrik.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 16)); // NOI18N
      radioListrik.setForeground(new java.awt.Color(255, 255, 255));
      radioListrik.setText("Teknik Instalasi Listrik");

      radioRpl.setBackground(new java.awt.Color(0, 204, 204));
      buttonGroup11.add(radioRpl);
      radioRpl.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 16)); // NOI18N
      radioRpl.setForeground(new java.awt.Color(255, 255, 255));
      radioRpl.setText("Rekayasa Perangkat Lunak");

      radioTkr.setBackground(new java.awt.Color(0, 204, 204));
      buttonGroup11.add(radioTkr);
      radioTkr.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 16)); // NOI18N
      radioTkr.setForeground(new java.awt.Color(255, 255, 255));
      radioTkr.setText("Teknik Kendaraan Ringan");

      radioMesin.setBackground(new java.awt.Color(0, 204, 204));
      buttonGroup11.add(radioMesin);
      radioMesin.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 16)); // NOI18N
      radioMesin.setForeground(new java.awt.Color(255, 255, 255));
      radioMesin.setText("Teknik Pemesinan");

      radioMM.setBackground(new java.awt.Color(0, 204, 204));
      buttonGroup11.add(radioMM);
      radioMM.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 16)); // NOI18N
      radioMM.setForeground(new java.awt.Color(255, 255, 255));
      radioMM.setText("Multimedia");

      javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
      jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(radioRpl)
               .addComponent(radioMesin)
               .addComponent(radioTkj)
               .addComponent(radioMM)
               .addComponent(radioTkr)
               .addComponent(radioListrik))
            .addContainerGap(115, Short.MAX_VALUE))
      );
      jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addComponent(radioRpl)
            .addGap(18, 18, 18)
            .addComponent(radioMesin)
            .addGap(18, 18, 18)
            .addComponent(radioTkr)
            .addGap(18, 18, 18)
            .addComponent(radioTkj)
            .addGap(18, 18, 18)
            .addComponent(radioMM)
            .addGap(18, 18, 18)
            .addComponent(radioListrik)
            .addContainerGap(15, Short.MAX_VALUE))
      );

      txtNama.setEditable(false);
      txtNama.setBackground(new java.awt.Color(0, 0, 0));
      txtNama.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
      txtNama.setForeground(new java.awt.Color(255, 255, 255));
      txtNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      txtAsalSekolah.setEditable(false);
      txtAsalSekolah.setBackground(new java.awt.Color(0, 0, 0));
      txtAsalSekolah.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
      txtAsalSekolah.setForeground(new java.awt.Color(255, 255, 255));
      txtAsalSekolah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      jPanel3.setBackground(new java.awt.Color(169, 224, 49));

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 737, Short.MAX_VALUE)
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 9, Short.MAX_VALUE)
      );

      lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      jLabel9.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 1, 14)); // NOI18N
      jLabel9.setForeground(new java.awt.Color(255, 255, 255));
      jLabel9.setText("ALAMAT");

      txtAlamat.setEditable(false);
      txtAlamat.setBackground(new java.awt.Color(0, 0, 0));
      txtAlamat.setColumns(20);
      txtAlamat.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
      txtAlamat.setForeground(new java.awt.Color(255, 255, 255));
      txtAlamat.setRows(5);
      txtAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
      jScrollPane1.setViewportView(txtAlamat);

      lblJurusan.setForeground(new java.awt.Color(255, 255, 255));
      lblJurusan.setText("0");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(31, 31, 31)
                  .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                  .addGap(27, 27, 27)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel1)
                           .addComponent(jLabel2)
                           .addComponent(jLabel3)
                           .addComponent(jLabel9))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(txtIdSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                           .addComponent(txtAsalSekolah)
                           .addComponent(txtNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGap(14, 14, 14)
                  .addComponent(lblJurusan)
                  .addGap(233, 233, 233)
                  .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGap(46, 46, 46))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel1)
                     .addComponent(txtIdSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel2)
                     .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel3)
                     .addComponent(txtAsalSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(14, 14, 14)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(41, 41, 41))))
               .addComponent(lblFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(37, 37, 37)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnSimpan)
               .addComponent(lblJurusan))
            .addGap(18, 18, 18))
      );

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(10, 10, 10))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
      Siswa siswa = new Siswa();
      getJurusan();

      if (lblJurusan.getText().equals("0") || txtRata.getText().equals("0")) {
         JOptionPane.showMessageDialog(null, "Data yang anda isi belum lengkap", "Peringatan", JOptionPane.ERROR_MESSAGE);
      } else {
         getJurusan();
         siswa.setNilai_bin(Double.valueOf(txtNilaiBin.getText()));
         siswa.setNilai_big(Double.valueOf(txtNilaiBig.getText()));
         siswa.setNilai_mtk(Double.valueOf(txtNilaiMtk.getText()));
         siswa.setNilai_ipa(Double.valueOf(txtNilaiIpa.getText()));
         siswa.setRata(Double.valueOf(txtRata.getText()));
         siswa.setId_siswa(txtIdSiswa.getText());
         siswa.getJurusan().setId_jurusan(getJurusan());
         siswa.saveNilaiSiswa();
         clearData();
         JOptionPane.showMessageDialog(null, "Pengisian data berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);
         this.setVisible(false);
      }
   }//GEN-LAST:event_btnSimpanActionPerformed

   private void btnHitungrataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungrataActionPerformed
      double nilai_bin = Double.valueOf(txtNilaiBin.getText());
      double nilai_big = Double.valueOf(txtNilaiBig.getText());
      double nilai_mtk = Double.valueOf(txtNilaiMtk.getText());
      double nilai_ipa = Double.valueOf(txtNilaiIpa.getText());
      double hitung_rata;

      hitung_rata = (nilai_bin + nilai_big + nilai_mtk + nilai_ipa) / 4;
      txtRata.setText(String.valueOf(hitung_rata));
   }//GEN-LAST:event_btnHitungrataActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(inputNilaiSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(inputNilaiSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(inputNilaiSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(inputNilaiSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new inputNilaiSiswa().setVisible(true);
         }
      });
   }


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnHitungrata;
   private javax.swing.JButton btnSimpan;
   private javax.swing.ButtonGroup buttonGroup11;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextField jTextField4;
   protected javax.swing.JLabel lblFoto;
   private javax.swing.JLabel lblJurusan;
   private javax.swing.JRadioButton radioListrik;
   private javax.swing.JRadioButton radioMM;
   private javax.swing.JRadioButton radioMesin;
   private javax.swing.JRadioButton radioRpl;
   private javax.swing.JRadioButton radioTkj;
   private javax.swing.JRadioButton radioTkr;
   public javax.swing.JTextArea txtAlamat;
   public javax.swing.JTextField txtAsalSekolah;
   public javax.swing.JTextField txtIdSiswa;
   public javax.swing.JTextField txtNama;
   private javax.swing.JTextField txtNilaiBig;
   private javax.swing.JTextField txtNilaiBin;
   private javax.swing.JTextField txtNilaiIpa;
   private javax.swing.JTextField txtNilaiMtk;
   private javax.swing.JTextField txtRata;
   // End of variables declaration//GEN-END:variables
}
