/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project.Frontend;

import Project.Backend.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gokpraz
 */
public class Login extends javax.swing.JFrame {

   /**
    * Creates new form Login
    */
   public Login() {
      initComponents();
      tampil_siswa();
   }

   void tampil_admin() {
      panelAdmin.setVisible(true);
      panelSiswa.setVisible(false);
      disabled_admin();
   }

   void tampil_siswa() {
      panelAdmin.setVisible(false);
      panelSiswa.setVisible(true);
      disabled_siswa();
      txtIdSiswa.setText("Masukan id siswa");
   }

   void disabled_siswa() {
      btnAdmin.setEnabled(true);
      btnSiswa.setEnabled(false);
   }

   void disabled_admin() {
      btnAdmin.setEnabled(false);
      btnSiswa.setEnabled(true);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      jList1 = new javax.swing.JList<>();
      jButton2 = new javax.swing.JButton();
      jPanel1 = new javax.swing.JPanel();
      panelAdmin = new javax.swing.JPanel();
      txtUsername = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      btnLoginAdmin = new javax.swing.JButton();
      txtPasswordAdmin = new javax.swing.JPasswordField();
      panelSiswa = new javax.swing.JPanel();
      txtIdSiswa = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      btnLoginSiswa = new javax.swing.JButton();
      btnSiswa = new javax.swing.JButton();
      jLabel3 = new javax.swing.JLabel();
      btnAdmin = new javax.swing.JButton();
      jLabel6 = new javax.swing.JLabel();

      jList1.setModel(new javax.swing.AbstractListModel<String>() {
         String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
         public int getSize() { return strings.length; }
         public String getElementAt(int i) { return strings[i]; }
      });
      jScrollPane1.setViewportView(jList1);

      jButton2.setText("jButton2");

      setTitle("LOGIN AREA");
      setAlwaysOnTop(true);
      setResizable(false);
      setType(java.awt.Window.Type.UTILITY);

      jPanel1.setBackground(new java.awt.Color(0, 0, 0));

      panelAdmin.setBackground(new java.awt.Color(0, 0, 0));

      txtUsername.setBackground(new java.awt.Color(0, 0, 0));
      txtUsername.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
      txtUsername.setForeground(new java.awt.Color(255, 255, 255));
      txtUsername.setText("Username");
      txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
      txtUsername.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtUsernameActionPerformed(evt);
         }
      });

      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Male_User_35px.png"))); // NOI18N

      jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Lock_35px.png"))); // NOI18N

      btnLoginAdmin.setBackground(new java.awt.Color(169, 224, 49));
      btnLoginAdmin.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
      btnLoginAdmin.setForeground(new java.awt.Color(0, 0, 0));
      btnLoginAdmin.setText("LOGIN");
      btnLoginAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      btnLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLoginAdminActionPerformed(evt);
         }
      });

      txtPasswordAdmin.setBackground(new java.awt.Color(0, 0, 0));
      txtPasswordAdmin.setForeground(new java.awt.Color(255, 255, 255));
      txtPasswordAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
      txtPasswordAdmin.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtPasswordAdminActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
      panelAdmin.setLayout(panelAdminLayout);
      panelAdminLayout.setHorizontalGroup(
         panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelAdminLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnLoginAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
               .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addGroup(panelAdminLayout.createSequentialGroup()
                     .addComponent(jLabel2)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(txtPasswordAdmin))
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAdminLayout.createSequentialGroup()
                     .addComponent(jLabel1)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(0, 21, Short.MAX_VALUE))
      );
      panelAdminLayout.setVerticalGroup(
         panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelAdminLayout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel1))
            .addGap(23, 23, 23)
            .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(34, Short.MAX_VALUE))
      );

      panelSiswa.setBackground(new java.awt.Color(0, 0, 0));

      txtIdSiswa.setBackground(new java.awt.Color(0, 0, 0));
      txtIdSiswa.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
      txtIdSiswa.setForeground(new java.awt.Color(255, 255, 255));
      txtIdSiswa.setText("Masukan id siswa");
      txtIdSiswa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
      txtIdSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            txtIdSiswaMouseClicked(evt);
         }
      });

      jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Lock_35px.png"))); // NOI18N

      btnLoginSiswa.setBackground(new java.awt.Color(169, 224, 49));
      btnLoginSiswa.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
      btnLoginSiswa.setForeground(new java.awt.Color(0, 0, 0));
      btnLoginSiswa.setText("LOGIN");
      btnLoginSiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      btnLoginSiswa.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLoginSiswaActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout panelSiswaLayout = new javax.swing.GroupLayout(panelSiswa);
      panelSiswa.setLayout(panelSiswaLayout);
      panelSiswaLayout.setHorizontalGroup(
         panelSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelSiswaLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(panelSiswaLayout.createSequentialGroup()
                  .addComponent(jLabel5)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtIdSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 9, Short.MAX_VALUE))
               .addComponent(btnLoginSiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      panelSiswaLayout.setVerticalGroup(
         panelSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelSiswaLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(txtIdSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel5))
            .addGap(49, 49, 49)
            .addComponent(btnLoginSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(34, 34, 34))
      );

      btnSiswa.setBackground(new java.awt.Color(169, 224, 49));
      btnSiswa.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
      btnSiswa.setForeground(new java.awt.Color(0, 0, 0));
      btnSiswa.setText("SISWA");
      btnSiswa.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSiswaActionPerformed(evt);
         }
      });

      jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(169, 224, 49));
      jLabel3.setText("OR");

      btnAdmin.setBackground(new java.awt.Color(169, 224, 49));
      btnAdmin.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
      btnAdmin.setForeground(new java.awt.Color(0, 0, 0));
      btnAdmin.setText("ADMIN");
      btnAdmin.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAdminActionPerformed(evt);
         }
      });

      jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_User_Shield_100px.png"))); // NOI18N

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(panelSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(panelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(58, 58, 58)
                  .addComponent(btnSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(3, 3, 3)
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(116, 116, 116)
            .addComponent(jLabel6)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(panelSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void btnLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAdminActionPerformed
      Admin admin = new Admin();
      String username = txtUsername.getText();
      String password = txtPasswordAdmin.getText();
      
      if (admin.loginAdmin(username, password)) {
         AdminForm adminForm = new AdminForm();
         Admin dataAdmin = admin.getByUserPass(username, password);

         adminForm.txtUsername.setText(dataAdmin.getUsername());
         adminForm.txtNama.setText(dataAdmin.getNama());
         adminForm.idFoto = txtUsername.getText();
         System.out.println(adminForm.idFoto);

         try {
            ImageIcon icon = new ImageIcon(new ImageIcon(getClass().getResource("/images/Admin/" + adminForm.idFoto + ".png"))
              .getImage().getScaledInstance(210, 270, Image.SCALE_SMOOTH));
            adminForm.lblFoto.setIcon(icon);
         } catch (Exception e) {
            System.out.println(e.getMessage());
         }
         adminForm.setVisible(true);
         this.setVisible(false);
         
      } else {
         JOptionPane.showMessageDialog(null, "Login gagal");
         txtPasswordAdmin.setText("");
         txtUsername.setText("");
      }

   }//GEN-LAST:event_btnLoginAdminActionPerformed

   private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
      // TODO add your handling code here:
      tampil_admin();
   }//GEN-LAST:event_btnAdminActionPerformed

   private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtUsernameActionPerformed

   private void btnLoginSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginSiswaActionPerformed
      Siswa siswa = new Siswa();
      if (siswa.loginSiswa(txtIdSiswa.getText())) {
         inputNilaiSiswa input = new inputNilaiSiswa();
         Siswa data = siswa.getById(txtIdSiswa.getText());
         input.txtIdSiswa.setText(data.getId_siswa());
         input.txtNama.setText(data.getNama());
         input.txtAlamat.setText(data.getAlamat());
         input.txtAsalSekolah.setText(data.getAsal_sekolah());
         input.idFoto = txtIdSiswa.getText();
         System.out.println(input.idFoto);

         try {
            ImageIcon icon = new ImageIcon(new ImageIcon(getClass().getResource("/images/Siswa/" + input.idFoto.toUpperCase() + ".png"))
              .getImage().getScaledInstance(246, 270, Image.SCALE_SMOOTH));
            input.lblFoto.setIcon(icon);
         } catch (Exception e) {
            System.out.println(e.getMessage());
         }

         input.setVisible(true);
         this.setVisible(false);
      } else {
         JOptionPane.showMessageDialog(null, "Login gagal", "Peringatan", JOptionPane.ERROR_MESSAGE);
      }
   }//GEN-LAST:event_btnLoginSiswaActionPerformed

   private void btnSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiswaActionPerformed
      // TODO add your handling code here:
      tampil_siswa();
   }//GEN-LAST:event_btnSiswaActionPerformed

   private void txtPasswordAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordAdminActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtPasswordAdminActionPerformed

   private void txtIdSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdSiswaMouseClicked
      txtIdSiswa.setText("");
   }//GEN-LAST:event_txtIdSiswaMouseClicked

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Login().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAdmin;
   private javax.swing.JButton btnLoginAdmin;
   private javax.swing.JButton btnLoginSiswa;
   private javax.swing.JButton btnSiswa;
   private javax.swing.JButton jButton2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JList<String> jList1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JPanel panelAdmin;
   private javax.swing.JPanel panelSiswa;
   private javax.swing.JTextField txtIdSiswa;
   private javax.swing.JPasswordField txtPasswordAdmin;
   private javax.swing.JTextField txtUsername;
   // End of variables declaration//GEN-END:variables
}
