/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project.Frontend;

import Project.Backend.*;

import MencobaUpload.CobaUpload;
import Project.Backend.Interface.*;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author WINDOWS 10
 */
public class PendaftaranSiswa extends javax.swing.JFrame implements Upload {

   private Image image;

   public PendaftaranSiswa() {
      initComponents();
      lblAcak.setVisible(false);
      lblAcak.setText(acakHuruf());
//      JOptionPane.showMessageDialog(null, lblAcak.getText());
   }

   @Override
   public BufferedImage resize(Image img, int height, int width) {
      Image tmp = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
      BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
      Graphics2D g2d = resized.createGraphics();
      g2d.drawImage(tmp, 0, 0, null);
      g2d.dispose();
      return resized;
   }

   @Override
   public ImageIcon ResizeImage(String ImagePath) {
      ImageIcon MyImage = new ImageIcon(ImagePath);
      Image img = MyImage.getImage();
      Image newImg = img.getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH);
      ImageIcon image = new ImageIcon(newImg);
      return image;
   }

   public String acakHuruf() {
      String acak = "";
      for (int i = 0; i < 5; i++) {
         Random r = new Random();
         char huruf = (char) (r.nextInt(26) + 'A');
         acak += huruf;
      }
      return acak;
   }

   public void clearData() {
      txtNama.setText("");
      txtAlamat.setText("");
      txtTempatLahir.setText("");
      txtAsalSekolah.setText("");
      txtFoto.setText("");
      radioLaki.setSelected(false);
      radioPerempuan.setSelected(false);
      lblFoto.setIcon(null);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      genderGroup = new javax.swing.ButtonGroup();
      jPanel1 = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      txtNama = new javax.swing.JTextField();
      txtTempatLahir = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      txtAlamat = new javax.swing.JTextArea();
      comboTanggal = new javax.swing.JComboBox<>();
      comboBulan = new javax.swing.JComboBox<>();
      comboTahun = new javax.swing.JComboBox<>();
      radioPerempuan = new javax.swing.JRadioButton();
      radioLaki = new javax.swing.JRadioButton();
      jLabel6 = new javax.swing.JLabel();
      lblFoto = new javax.swing.JLabel();
      txtFoto = new javax.swing.JTextField();
      txtAsalSekolah = new javax.swing.JTextField();
      btnCariFile = new javax.swing.JButton();
      btnSimpan = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      lblAcak = new javax.swing.JLabel();

      setTitle("Pendaftaran Siswa");
      setAlwaysOnTop(true);
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(169, 224, 49));

      jPanel2.setBackground(new java.awt.Color(0, 0, 0));

      jLabel1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(255, 255, 255));
      jLabel1.setText("NAMA");

      jLabel2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(255, 255, 255));
      jLabel2.setText("TEMPAT LAHIR");

      jLabel3.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(255, 255, 255));
      jLabel3.setText("TANGGAL LAHIR");

      jLabel4.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(255, 255, 255));
      jLabel4.setText("ALAMAT");

      txtNama.setBackground(new java.awt.Color(0, 0, 0));
      txtNama.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 14)); // NOI18N
      txtNama.setForeground(new java.awt.Color(255, 255, 255));
      txtNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      txtTempatLahir.setBackground(new java.awt.Color(0, 0, 0));
      txtTempatLahir.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 14)); // NOI18N
      txtTempatLahir.setForeground(new java.awt.Color(255, 255, 255));
      txtTempatLahir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      jLabel5.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(255, 255, 255));
      jLabel5.setText("JENIS KELAMIN");

      txtAlamat.setBackground(new java.awt.Color(0, 0, 0));
      txtAlamat.setColumns(20);
      txtAlamat.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 14)); // NOI18N
      txtAlamat.setForeground(new java.awt.Color(255, 255, 255));
      txtAlamat.setLineWrap(true);
      txtAlamat.setRows(5);
      txtAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
      jScrollPane1.setViewportView(txtAlamat);

      comboTanggal.setBackground(new java.awt.Color(169, 224, 49));
      comboTanggal.setForeground(new java.awt.Color(255, 255, 255));
      comboTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

      comboBulan.setBackground(new java.awt.Color(169, 224, 49));
      comboBulan.setForeground(new java.awt.Color(255, 255, 255));
      comboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

      comboTahun.setBackground(new java.awt.Color(169, 224, 49));
      comboTahun.setForeground(new java.awt.Color(255, 255, 255));
      comboTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2016", "2017", "2018", "2019" }));

      radioPerempuan.setBackground(new java.awt.Color(0, 0, 0));
      genderGroup.add(radioPerempuan);
      radioPerempuan.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
      radioPerempuan.setForeground(new java.awt.Color(255, 255, 255));
      radioPerempuan.setText("Perempuan");

      radioLaki.setBackground(new java.awt.Color(0, 0, 0));
      genderGroup.add(radioLaki);
      radioLaki.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
      radioLaki.setForeground(new java.awt.Color(255, 255, 255));
      radioLaki.setText("Laki-laki");

      jLabel6.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
      jLabel6.setForeground(new java.awt.Color(255, 255, 255));
      jLabel6.setText("ASAL SEKOLAH");

      lblFoto.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 14)); // NOI18N
      lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      txtFoto.setBackground(new java.awt.Color(0, 0, 0));
      txtFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
      txtFoto.setEnabled(false);
      txtFoto.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtFotoActionPerformed(evt);
         }
      });

      txtAsalSekolah.setBackground(new java.awt.Color(0, 0, 0));
      txtAsalSekolah.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 14)); // NOI18N
      txtAsalSekolah.setForeground(new java.awt.Color(255, 255, 255));
      txtAsalSekolah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      btnCariFile.setText("...");
      btnCariFile.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCariFileActionPerformed(evt);
         }
      });

      btnSimpan.setBackground(new java.awt.Color(169, 224, 49));
      btnSimpan.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
      btnSimpan.setForeground(new java.awt.Color(0, 0, 0));
      btnSimpan.setText("Simpan");
      btnSimpan.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSimpanActionPerformed(evt);
         }
      });

      jButton3.setBackground(new java.awt.Color(169, 224, 49));
      jButton3.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
      jButton3.setForeground(new java.awt.Color(0, 0, 0));
      jButton3.setText("Kembali");
      jButton3.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
         }
      });

      lblAcak.setForeground(new java.awt.Color(255, 255, 255));
      lblAcak.setText("jLabel7");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1)
               .addComponent(jLabel2)
               .addComponent(jLabel3)
               .addComponent(jLabel4)
               .addComponent(jLabel5)
               .addComponent(jLabel6))
            .addGap(30, 30, 30)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel2Layout.createSequentialGroup()
                     .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(txtNama)
                           .addComponent(txtTempatLahir)
                           .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                           .addGroup(jPanel2Layout.createSequentialGroup()
                              .addComponent(comboTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(comboTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(8, 8, 8)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                           .addComponent(radioLaki)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(radioPerempuan)))
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                     .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                           .addComponent(txtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                           .addComponent(btnCariFile))))
                  .addComponent(txtAsalSekolah))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(12, 12, 12))
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(204, 204, 204)
            .addComponent(lblAcak)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblAcak)
            .addGap(5, 5, 5)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jLabel1)
                     .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel2))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(comboTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(comboTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel4)
                     .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(radioPerempuan)
               .addComponent(radioLaki)
               .addComponent(jLabel5)
               .addComponent(txtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnCariFile))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(txtAsalSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
               .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      this.setVisible(false);
   }//GEN-LAST:event_jButton3ActionPerformed

   private void btnCariFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariFileActionPerformed
      JFileChooser chooser = new JFileChooser(System.getProperty("user  .home"));
      chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
      chooser.setFileFilter(new FileNameExtensionFilter("jpg|png|bmp", "jpg", "png", "bmp"));

      if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
         try {
            File file = chooser.getSelectedFile();
            image = ImageIO.read(file);
            String path = file.getAbsolutePath();
            lblFoto.setIcon(ResizeImage(path));
            txtFoto.setText(file.getAbsolutePath());
         } catch (IOException ex) {
            Logger.getLogger(CobaUpload.class.getName()).log(Level.SEVERE, null, ex);
         }
      }
   }//GEN-LAST:event_btnCariFileActionPerformed

   private void txtFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFotoActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtFotoActionPerformed

   private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
      Object options[] = {"Ya", "Tidak"};
      int result = JOptionPane.showOptionDialog(this, "Apakah data yang ada inputkan sudah benar ?", "Konfirmasi",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
      
      if (result == JOptionPane.YES_OPTION) {
         String tanggal = comboTahun.getSelectedItem() + "-" + comboBulan.getSelectedItem() + "-" + comboTanggal.getSelectedItem();
         Siswa siswa = new Siswa();
         TampilIdSiswa tampil = new TampilIdSiswa();
         String jk;
         if (radioLaki.isSelected()) {
            jk = "Laki-laki";
         } else {
            jk = "Perempuan";
         }

         siswa.setId_siswa(lblAcak.getText());
         siswa.setNama(txtNama.getText());
         siswa.setTempat(txtTempatLahir.getText());
         siswa.setTgl_lahir(tanggal);
         siswa.setAlamat(txtAlamat.getText());
         siswa.setJk(jk);
         siswa.setAsal_sekolah(txtAsalSekolah.getText());
         siswa.setFoto(lblAcak.getText() + ".png");

         try {
            BufferedImage resized = resize(image, 500, 400);
            File output = new File("/media/gokpraz/Data 2/Data/Kuliah/Semester 3/Pemograman Berbasis Objek (PBO)/Project Akhir/src/images/Siswa/" + lblAcak.getText() + ".png");
            ImageIO.write(resized, "png", output);
         } catch (IOException ex) {
            Logger.getLogger(CobaUpload.class.getName()).log(Level.SEVERE, null, ex);
         }

         siswa.save();
         clearData();
         this.setVisible(false);

         tampil.lblIdSiswa.setText(lblAcak.getText());
         tampil.setVisible(true);
      }

   }//GEN-LAST:event_btnSimpanActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(PendaftaranSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(PendaftaranSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(PendaftaranSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(PendaftaranSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new PendaftaranSiswa().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnCariFile;
   private javax.swing.JButton btnSimpan;
   private javax.swing.JComboBox<String> comboBulan;
   private javax.swing.JComboBox<String> comboTahun;
   private javax.swing.JComboBox<String> comboTanggal;
   private javax.swing.ButtonGroup genderGroup;
   private javax.swing.JButton jButton3;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JLabel lblAcak;
   private javax.swing.JLabel lblFoto;
   private javax.swing.JRadioButton radioLaki;
   private javax.swing.JRadioButton radioPerempuan;
   private javax.swing.JTextArea txtAlamat;
   private javax.swing.JTextField txtAsalSekolah;
   private javax.swing.JTextField txtFoto;
   private javax.swing.JTextField txtNama;
   private javax.swing.JTextField txtTempatLahir;
   // End of variables declaration//GEN-END:variables

}
