/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project.Frontend;

import Project.Backend.*;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author WINDOWS 10
 */
public class TampilJurusan extends javax.swing.JFrame {

   public TampilJurusan() {
      initComponents();
      clearData();
   }

   public void tampil_data_jurusan(int id_jurusan) {
      Jurusan jurusan = new Jurusan();
      Jurusan data = jurusan.getById(id_jurusan);
      txtNama.setText(data.getNama());
      txtSingkatan.setText(data.getSingkatan());
      txtKeterangan.setText(data.getKeterangan());
      ImageIcon icon = new ImageIcon(new ImageIcon(getClass().getResource("/images/Jurusan/" + txtSingkatan.getText().toUpperCase() + ".png"))
        .getImage().getScaledInstance(221, 322, Image.SCALE_SMOOTH));
      lblFoto.setIcon(icon);
   }
   
   public void clearData(){
      txtNama.setText("");
      txtSingkatan.setText("");
      txtKeterangan.setText("");
      lblFoto.setIcon(null);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      btnRPL = new javax.swing.JButton();
      btnMM = new javax.swing.JButton();
      btnTKJ = new javax.swing.JButton();
      btnListrik = new javax.swing.JButton();
      btnTKR = new javax.swing.JButton();
      btnTPM = new javax.swing.JButton();
      lblFoto = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jButton7 = new javax.swing.JButton();
      jLabel5 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      txtKeterangan = new javax.swing.JTextArea();
      txtNama = new javax.swing.JTextField();
      txtSingkatan = new javax.swing.JTextField();

      setTitle("Jurusan");
      setAlwaysOnTop(true);
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(169, 224, 49));

      jPanel2.setBackground(new java.awt.Color(0, 0, 0));

      btnRPL.setBackground(new java.awt.Color(169, 224, 49));
      btnRPL.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
      btnRPL.setForeground(new java.awt.Color(0, 0, 0));
      btnRPL.setText("REKAYASA PERANGKAT LUNAK");
      btnRPL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      btnRPL.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRPLActionPerformed(evt);
         }
      });

      btnMM.setBackground(new java.awt.Color(169, 224, 49));
      btnMM.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
      btnMM.setForeground(new java.awt.Color(0, 0, 0));
      btnMM.setText("MULTIMEDIA");
      btnMM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      btnMM.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnMMActionPerformed(evt);
         }
      });

      btnTKJ.setBackground(new java.awt.Color(169, 224, 49));
      btnTKJ.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
      btnTKJ.setForeground(new java.awt.Color(0, 0, 0));
      btnTKJ.setText("TEKNIK  KOMPUTER JARINGAN");
      btnTKJ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      btnTKJ.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTKJActionPerformed(evt);
         }
      });

      btnListrik.setBackground(new java.awt.Color(169, 224, 49));
      btnListrik.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
      btnListrik.setForeground(new java.awt.Color(0, 0, 0));
      btnListrik.setText("TEKNIK INSTALASI LISTRIK");
      btnListrik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      btnListrik.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnListrikActionPerformed(evt);
         }
      });

      btnTKR.setBackground(new java.awt.Color(169, 224, 49));
      btnTKR.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
      btnTKR.setForeground(new java.awt.Color(0, 0, 0));
      btnTKR.setText("TEKNIK KENDARAAN RINGAN");
      btnTKR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      btnTKR.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTKRActionPerformed(evt);
         }
      });

      btnTPM.setBackground(new java.awt.Color(169, 224, 49));
      btnTPM.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
      btnTPM.setForeground(new java.awt.Color(0, 0, 0));
      btnTPM.setText("TEKNIK PEMESINAN");
      btnTPM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      btnTPM.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTPMActionPerformed(evt);
         }
      });

      lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      jLabel2.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 1, 18)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(255, 255, 255));
      jLabel2.setText("NAMA JURUSAN ");

      jButton7.setBackground(new java.awt.Color(169, 224, 49));
      jButton7.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
      jButton7.setForeground(new java.awt.Color(0, 0, 0));
      jButton7.setText("KEMBALI");
      jButton7.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
         }
      });

      jLabel5.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 1, 18)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(255, 255, 255));
      jLabel5.setText("KETERANGAN");

      jLabel7.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 1, 18)); // NOI18N
      jLabel7.setForeground(new java.awt.Color(255, 255, 255));
      jLabel7.setText("SINGKATAN");

      txtKeterangan.setEditable(false);
      txtKeterangan.setBackground(new java.awt.Color(0, 0, 0));
      txtKeterangan.setColumns(20);
      txtKeterangan.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
      txtKeterangan.setForeground(new java.awt.Color(255, 255, 255));
      txtKeterangan.setRows(5);
      txtKeterangan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
      jScrollPane1.setViewportView(txtKeterangan);

      txtNama.setEditable(false);
      txtNama.setBackground(new java.awt.Color(0, 0, 0));
      txtNama.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
      txtNama.setForeground(new java.awt.Color(255, 255, 255));
      txtNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      txtSingkatan.setEditable(false);
      txtSingkatan.setBackground(new java.awt.Color(0, 0, 0));
      txtSingkatan.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
      txtSingkatan.setForeground(new java.awt.Color(255, 255, 255));
      txtSingkatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(btnTKR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(btnTKJ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(btnMM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(btnRPL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                  .addGroup(jPanel2Layout.createSequentialGroup()
                     .addGap(6, 6, 6)
                     .addComponent(btnListrik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
               .addComponent(btnTPM, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGap(18, 18, 18)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jLabel2)
                     .addComponent(jLabel5)
                     .addComponent(jLabel7)
                     .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                     .addComponent(txtNama)
                     .addComponent(txtSingkatan))
                  .addContainerGap(15, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(60, 60, 60))))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addContainerGap(63, Short.MAX_VALUE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel2)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jLabel7)
                  .addGap(2, 2, 2)
                  .addComponent(txtSingkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(12, 12, 12)
                  .addComponent(jLabel5)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jScrollPane1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(12, 12, 12))))
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(35, 35, 35)
            .addComponent(btnRPL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnTPM)
            .addGap(18, 18, 18)
            .addComponent(btnTKR)
            .addGap(26, 26, 26)
            .addComponent(btnTKJ)
            .addGap(18, 18, 18)
            .addComponent(btnMM)
            .addGap(18, 18, 18)
            .addComponent(btnListrik)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void btnRPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRPLActionPerformed
      tampil_data_jurusan(1);
   }//GEN-LAST:event_btnRPLActionPerformed

   private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      this.setVisible(false);
      clearData();
   }//GEN-LAST:event_jButton7ActionPerformed

   private void btnTKJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKJActionPerformed
      tampil_data_jurusan(4);
   }//GEN-LAST:event_btnTKJActionPerformed

   private void btnTPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTPMActionPerformed
      tampil_data_jurusan(2);
   }//GEN-LAST:event_btnTPMActionPerformed

   private void btnTKRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKRActionPerformed
      tampil_data_jurusan(3);
   }//GEN-LAST:event_btnTKRActionPerformed

   private void btnMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMActionPerformed
      tampil_data_jurusan(5);
   }//GEN-LAST:event_btnMMActionPerformed

   private void btnListrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListrikActionPerformed
      tampil_data_jurusan(6);
   }//GEN-LAST:event_btnListrikActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(TampilJurusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(TampilJurusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(TampilJurusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(TampilJurusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new TampilJurusan().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnListrik;
   private javax.swing.JButton btnMM;
   private javax.swing.JButton btnRPL;
   private javax.swing.JButton btnTKJ;
   private javax.swing.JButton btnTKR;
   private javax.swing.JButton btnTPM;
   private javax.swing.JButton jButton7;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JLabel lblFoto;
   private javax.swing.JTextArea txtKeterangan;
   private javax.swing.JTextField txtNama;
   private javax.swing.JTextField txtSingkatan;
   // End of variables declaration//GEN-END:variables
}
